package com.stream.practice.basic;

import lombok.Getter;
import org.springframework.stereotype.Component;

import java.util.List;

@Getter
@Component
public class AppleBox {
    private final List<Apple> apples;

    private AppleBox() {
        this.apples = List.of(
                Apple.of(142, Color.BLACK, SugarGrade.LOW, 2000),
                Apple.of(133, Color.RED, SugarGrade.LOW, 1900),
                Apple.of(113, Color.WHITE, SugarGrade.MIDDLE, 1600),
                Apple.of(130, Color.RED, SugarGrade.HIGH, 1000),
                Apple.of(143, Color.BLACK, SugarGrade.MIDDLE, 1500),
                Apple.of(108, Color.BLACK, SugarGrade.HIGH, 1200),
                Apple.of(108, Color.BLACK, SugarGrade.MIDDLE, 1300),
                Apple.of(101, Color.BLACK, SugarGrade.HIGH, 1400),
                Apple.of(110, Color.GREEN, SugarGrade.HIGH, 1400),
                Apple.of(125, Color.GREEN, SugarGrade.LOW, 1400),
                Apple.of(132, Color.BLACK, SugarGrade.MIDDLE, 1200),
                Apple.of(141, Color.BLACK, SugarGrade.LOW, 1500),
                Apple.of(149, Color.GREEN, SugarGrade.MIDDLE, 1400),
                Apple.of(114, Color.GREEN, SugarGrade.LOW, 1100),
                Apple.of(127, Color.BLACK, SugarGrade.MIDDLE, 1100),
                Apple.of(139, Color.BLACK, SugarGrade.MIDDLE, 1300),
                Apple.of(124, Color.WHITE, SugarGrade.LOW, 1400),
                Apple.of(106, Color.GREEN, SugarGrade.LOW, 1800),
                Apple.of(148, Color.RED, SugarGrade.LOW, 1900),
                Apple.of(119, Color.WHITE, SugarGrade.MIDDLE, 1200),
                Apple.of(111, Color.RED, SugarGrade.HIGH, 1100),
                Apple.of(148, Color.GREEN, SugarGrade.LOW, 1800),
                Apple.of(118, Color.GREEN, SugarGrade.HIGH, 1800),
                Apple.of(113, Color.GREEN, SugarGrade.MIDDLE, 1900),
                Apple.of(119, Color.BLACK, SugarGrade.LOW, 2000),
                Apple.of(140, Color.BLACK, SugarGrade.MIDDLE, 1300),
                Apple.of(135, Color.BLACK, SugarGrade.HIGH, 1400),
                Apple.of(136, Color.GREEN, SugarGrade.MIDDLE, 1000),
                Apple.of(110, Color.BLACK, SugarGrade.MIDDLE, 1000),
                Apple.of(131, Color.WHITE, SugarGrade.MIDDLE, 1500),
                Apple.of(113, Color.RED, SugarGrade.HIGH, 1800),
                Apple.of(100, Color.RED, SugarGrade.LOW, 1400),
                Apple.of(117, Color.WHITE, SugarGrade.LOW, 1200),
                Apple.of(122, Color.WHITE, SugarGrade.MIDDLE, 1500),
                Apple.of(116, Color.GREEN, SugarGrade.LOW, 1500),
                Apple.of(113, Color.WHITE, SugarGrade.HIGH, 1500),
                Apple.of(117, Color.GREEN, SugarGrade.HIGH, 1700),
                Apple.of(127, Color.BLACK, SugarGrade.HIGH, 1100),
                Apple.of(119, Color.GREEN, SugarGrade.MIDDLE, 1900),
                Apple.of(109, Color.BLACK, SugarGrade.HIGH, 1300),
                Apple.of(131, Color.BLACK, SugarGrade.LOW, 1300),
                Apple.of(112, Color.GREEN, SugarGrade.MIDDLE, 1300),
                Apple.of(149, Color.RED, SugarGrade.LOW, 1800),
                Apple.of(106, Color.GREEN, SugarGrade.LOW, 1500),
                Apple.of(115, Color.BLACK, SugarGrade.MIDDLE, 1200),
                Apple.of(132, Color.RED, SugarGrade.LOW, 1800),
                Apple.of(142, Color.BLACK, SugarGrade.HIGH, 1400),
                Apple.of(123, Color.GREEN, SugarGrade.LOW, 1400),
                Apple.of(126, Color.GREEN, SugarGrade.LOW, 1300),
                Apple.of(147, Color.RED, SugarGrade.HIGH, 1100),
                Apple.of(127, Color.BLACK, SugarGrade.LOW, 1000),
                Apple.of(100, Color.GREEN, SugarGrade.MIDDLE, 1500),
                Apple.of(113, Color.BLACK, SugarGrade.MIDDLE, 2000),
                Apple.of(145, Color.WHITE, SugarGrade.LOW, 1400),
                Apple.of(134, Color.WHITE, SugarGrade.MIDDLE, 1600),
                Apple.of(130, Color.BLACK, SugarGrade.LOW, 1600),
                Apple.of(120, Color.BLACK, SugarGrade.LOW, 1400),
                Apple.of(107, Color.RED, SugarGrade.MIDDLE, 1600),
                Apple.of(147, Color.BLACK, SugarGrade.HIGH, 1600),
                Apple.of(114, Color.GREEN, SugarGrade.LOW, 1300),
                Apple.of(107, Color.RED, SugarGrade.MIDDLE, 1700),
                Apple.of(117, Color.GREEN, SugarGrade.HIGH, 1800),
                Apple.of(130, Color.WHITE, SugarGrade.HIGH, 1100),
                Apple.of(105, Color.BLACK, SugarGrade.HIGH, 1500),
                Apple.of(130, Color.WHITE, SugarGrade.LOW, 1200),
                Apple.of(133, Color.WHITE, SugarGrade.LOW, 1300),
                Apple.of(132, Color.GREEN, SugarGrade.LOW, 1200),
                Apple.of(141, Color.BLACK, SugarGrade.MIDDLE, 1800),
                Apple.of(124, Color.WHITE, SugarGrade.HIGH, 1400),
                Apple.of(135, Color.RED, SugarGrade.MIDDLE, 1400),
                Apple.of(104, Color.BLACK, SugarGrade.HIGH, 1600),
                Apple.of(136, Color.RED, SugarGrade.HIGH, 1500),
                Apple.of(101, Color.GREEN, SugarGrade.LOW, 1500),
                Apple.of(150, Color.GREEN, SugarGrade.MIDDLE, 1200),
                Apple.of(142, Color.WHITE, SugarGrade.MIDDLE, 1500),
                Apple.of(104, Color.GREEN, SugarGrade.MIDDLE, 1900),
                Apple.of(105, Color.RED, SugarGrade.MIDDLE, 1600),
                Apple.of(126, Color.WHITE, SugarGrade.MIDDLE, 1500),
                Apple.of(101, Color.GREEN, SugarGrade.LOW, 1600),
                Apple.of(139, Color.RED, SugarGrade.LOW, 1600),
                Apple.of(145, Color.WHITE, SugarGrade.HIGH, 1500),
                Apple.of(147, Color.RED, SugarGrade.HIGH, 1300),
                Apple.of(137, Color.GREEN, SugarGrade.HIGH, 1600),
                Apple.of(125, Color.GREEN, SugarGrade.LOW, 1200),
                Apple.of(141, Color.BLACK, SugarGrade.MIDDLE, 1300),
                Apple.of(149, Color.RED, SugarGrade.MIDDLE, 1800),
                Apple.of(140, Color.WHITE, SugarGrade.HIGH, 1100),
                Apple.of(150, Color.BLACK, SugarGrade.MIDDLE, 1200),
                Apple.of(137, Color.WHITE, SugarGrade.MIDDLE, 2000),
                Apple.of(137, Color.BLACK, SugarGrade.LOW, 1100),
                Apple.of(104, Color.GREEN, SugarGrade.MIDDLE, 1900),
                Apple.of(136, Color.WHITE, SugarGrade.LOW, 1400),
                Apple.of(120, Color.BLACK, SugarGrade.MIDDLE, 1400),
                Apple.of(140, Color.BLACK, SugarGrade.MIDDLE, 1700),
                Apple.of(126, Color.BLACK, SugarGrade.LOW, 1400),
                Apple.of(125, Color.WHITE, SugarGrade.LOW, 1000),
                Apple.of(132, Color.RED, SugarGrade.HIGH, 1800),
                Apple.of(138, Color.BLACK, SugarGrade.MIDDLE, 1700),
                Apple.of(114, Color.WHITE, SugarGrade.HIGH, 1500),
                Apple.of(108, Color.RED, SugarGrade.LOW, 1800)
        );
    }

    public static AppleBox create() {
        return new AppleBox();
    }
}
